### ISSUE TITLE
Feature request: rounded corner

### ISSUE THREAD

**Issue by brainwo** [hhourani27/asciip#1]
These Unicode characters can be used to make rounded corners: `╭`, `╮`, `╰`, `╯`.

Example:
Notice the "Heap" box
```
                                     pseudo isolate for
                                     shared immutable objects
                                     like null, true, false.
                                     ┌────────────┐
                                     │ VM Isolate │       heaps can reference
                                     │ ╭────────╮ │       vm-isolate heap.
                            ┏━━━━━━━━━▶│ Heap   │◀━━━━━━━━━━━━━━━━┓
                            ┃        │ ╰────────╯ │               ┃
                            ┃        └────────────┘               ┃
                            ┃                                     ┃
  ┌─────────────────────────┃────────┐            ┌───────────────┃──────────────────┐
  │ IsolateGroup            ┃        │            │ IsolateGroup  ┃                  │
  │                         ┃        │            │               ┃                  │
  │ ╭───────────────────────┃──────╮ │            │ ╭─────────────┃────────────────╮ │
  │ │ GC managed Heap              ┅┅┅┅┅┅┅┅╳┅┅┅┅┅┅┅▶│ GC managed Heap              │ │
  │ ╰──────────────────────────────╯ │ no cross   │ ╰──────────────────────────────╯ │
  │  ┌─────────┐     ┌─────────┐     │ group      │  ┌─────────┐     ┌─────────┐     │
  │  │┌─────────┐    │┌─────────┐    │ references │  │┌─────────┐    │┌─────────┐    │
  │  ││┌─────────┐   ││┌─────────┐   │            │  ││┌─────────┐   ││┌─────────┐   │
  │  │││Isolate  │   │││         │   │            │  │││Isolate  │   │││         │   │
  │  │││         │   │││         │   │            │  │││         │   │││         │   │
  │  │││ globals │   │││ helper  │   │            │  │││ globals │   │││ helper  │   │
  │  │││         │   │││ thread  │   │            │  │││         │   │││ thread  │   │
  │  └││ mutator │   └││         │   │            │  └││ mutator │   └││         │   │
  │   └│ thread  │    └│         │   │            │   └│ thread  │    └│         │   │
  │    └─────────┘     └─────────┘   │            │    └─────────┘     └─────────┘   │
  └──────────────────────────────────┘            └──────────────────────────────────┘
  ```

**Comment by hhourani27** [comment]
Interesting. It should be doable. I'll try working on it during the weekend.

**Comment by julemand101** [comment]
The example comes from this page which are also a good inspiration for what is possible when using ASCII/UTF-8 for drawing figures: https://mrale.ph/dartvm/

**Comment by hhourani27** [comment]
@julemand101 Thanks for the link. I have a long list of features and styles that I wanted to implement (incl. rounded corners). However, I was waiting for user feedback to prioritize them. If there's a specific feature that you're missing, don't hesitate to create an issue.

**Comment by hhourani27** [comment]
Ok as I checked there are not "Light" and "Double" variants of those [unicode characters](https://www.unicode.org/charts/nameslist/n_2500.html) `╭ ╮╯╰ `

So either I 
1. Add a new option: **Corner style**, values: _ASCII_ `+` , _Square_ `┌` , _Rounded_ `╭`).
But we will have this result with different "Line style"
![image](https://github.com/user-attachments/assets/c2f13ee6-52a8-4a3e-98dc-030adcb702b3)
2. Add a new value for **Line style** : _Light rounded_
3. ~~Create a new shape Rounded rectangle~~ ( it would be good to apply rounded corners to multi-line segments)

I am leaning toward option (2). I will try it

**Comment by hhourani27** [comment]
Here you go, I just deployed v0.5.0 with the new feature

![image](https://github.com/user-attachments/assets/361d6c5c-e459-4fcd-8b64-3946a614fae7)

I'll wait a bit for your feedback before closing this issue.

@brainwo @julemand101 Thank you for this first issue! I would love if you can give me feedback on my tool and maybe ways to improve it. cheers!

**Comment by brainwo** [comment]
Looks cool to me
